apiVersion: apps/v1 #Deployment
kind: Deployment
metadata:
  name: library-deployment
  namespace : default 
  labels:
    app: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
        - name: library
          image: satyasibasahoo/library@sha256:a534dcb9a101253bf79cdbf841165551e634d583a61f1598fa3015b5d79dd589 #change to redirecftion container image
          ports:
            - containerPort: 9000
              name: http 
---
apiVersion: v1 #Service
kind: Service
metadata:
  name: library
  namespace: default
spec:
  selector:
    app: library
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000 
      name: http
  type: NodePort
---